# Generated by Django 4.2.5 on 2023-09-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('assistant', 'Library Assistant'), ('helper', 'Library Helper'), ('digital', 'Digital Library Employee')], max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
