# Generated by Django 4.2.5 on 2023-09-19 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('assistant', 'Library Assistant'), ('helper', 'Library Helper'), ('digital', 'Digital Library Employee')], max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeekStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(choices=[('general', 'General'), ('morning', 'Morning'), ('night', 'Night'), ('off', 'Off')], max_length=10)),
                ('tue', models.CharField(choices=[('general', 'General'), ('morning', 'Morning'), ('night', 'Night'), ('off', 'Off')], max_length=10)),
                ('wed', models.CharField(choices=[('general', 'General'), ('morning', 'Morning'), ('night', 'Night'), ('off', 'Off')], max_length=10)),
                ('thu', models.CharField(choices=[('general', 'General'), ('morning', 'Morning'), ('night', 'Night'), ('off', 'Off')], max_length=10)),
                ('fri', models.CharField(choices=[('general', 'General'), ('morning', 'Morning'), ('night', 'Night'), ('off', 'Off')], max_length=10)),
                ('sat', models.CharField(choices=[('general', 'General'), ('morning', 'Morning'), ('night', 'Night'), ('off', 'Off')], max_length=10)),
                ('sun', models.CharField(choices=[('general', 'General'), ('morning', 'Morning'), ('night', 'Night'), ('off', 'Off')], max_length=10)),
                ('date_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.datewindow')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.employee')),
            ],
        ),
    ]
